// <auto-generated />
using System;
using JCExamenP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JCExamenP1.Migrations
{
    [DbContext(typeof(JCExamenP1Context))]
    partial class JCExamenP1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JCExamenP1.Models.JCordero", b =>
                {
                    b.Property<int>("JCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JCId"), 1L, 1);

                    b.Property<DateTime>("FechaFabriacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("JCModelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("JCPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("JCRemanofacturado")
                        .HasColumnType("bit");

                    b.HasKey("JCId");

                    b.ToTable("JCordero");
                });
#pragma warning restore 612, 618
        }
    }
}
